In [11]:
import psycopg2 as pg2
import pandas as pd
import pprint

In [3]:
conn = pg2.connect(dbname='boardgames', user='postgres', host='localhost', port='5432', password='omgiroxkbye')

In [4]:
cur = conn.cursor()

In [5]:
query = '''select column_name,data_type 
from information_schema.columns 
where table_name = 'BoardGames';'''

In [6]:
cur.execute(query)

In [7]:
columns = cur.fetchall()

In [8]:
len(columns)

81

In [13]:
pprint.pprint(columns)

[('stats.subtype.videogame.pos', 'real'),
 ('stats.family.familygames.pos', 'real'),
 ('stats.family.partygames.bayesaverage', 'real'),
 ('stats.family.partygames.pos', 'real'),
 ('stats.family.strategygames.bayesaverage', 'real'),
 ('stats.family.strategygames.pos', 'real'),
 ('stats.family.thematic.bayesaverage', 'real'),
 ('stats.family.thematic.pos', 'real'),
 ('stats.family.wargames.bayesaverage', 'real'),
 ('stats.family.wargames.pos', 'real'),
 ('stats.median', 'real'),
 ('stats.numcomments', 'real'),
 ('stats.numweights', 'real'),
 ('stats.owned', 'real'),
 ('stats.stddev', 'real'),
 ('stats.subtype.boardgame.bayesaverage', 'real'),
 ('stats.subtype.boardgame.pos', 'real'),
 ('stats.trading', 'real'),
 ('stats.usersrated', 'real'),
 ('stats.wanting', 'real'),
 ('stats.wishing', 'real'),
 ('stats.family.amiga.bayesaverage', 'real'),
 ('stats.family.amiga.pos', 'real'),
 ('stats.family.arcade.bayesaverage', 'real'),
 ('stats.family.arcade.pos', 'real'),
 ('stats.family.atarist.bayesaverage', 'real'),
 ('stats.family.atarist.pos', 'real'),
 ('stats.family.commodore64.bayesaverage', 'real'),
 ('stats.family.commodore64.pos', 'real'),
 ('stats.subtype.rpgitem.bayesaverage', 'real'),
 ('stats.subtype.rpgitem.pos', 'real'),
 ('stats.subtype.videogame.bayesaverage', 'real'),
 ('details.maxplayers', 'integer'),
 ('details.maxplaytime', 'integer'),
 ('details.minage', 'integer'),
 ('details.minplayers', 'integer'),
 ('details.minplaytime', 'integer'),
 ('details.playingtime', 'integer'),
 ('details.yearpublished', 'integer'),
 ('attributes.total', 'real'),
 ('stats.average', 'real'),
 ('stats.averageweight', 'real'),
 ('stats.bayesaverage', 'real'),
 ('stats.family.abstracts.bayesaverage', 'real'),
 ('stats.family.abstracts.pos', 'real'),
 ('stats.family.cgs.bayesaverage', 'real'),
 ('stats.family.cgs.pos', 'real'),
 ('stats.family.childrensgames.bayesaverage', 'real'),
 ('stats.family.childrensgames.pos', 'real'),
 ('stats.family.familygames.bayesaverage', 'real'),
 ('game.id', 'text'),
 ('game.type', 'text'),
 ('details.description', 'text'),
 ('details.image', 'text'),
 ('polls.suggested_numplayers.6', 'text'),
 ('polls.suggested_numplayers.7', 'text'),
 ('polls.suggested_numplayers.8', 'text'),
 ('polls.suggested_numplayers.9', 'text'),
 ('polls.suggested_numplayers.Over', 'text'),
 ('details.name', 'text'),
 ('polls.suggested_playerage', 'text'),
 ('details.thumbnail', 'text'),
 ('attributes.t.links.concat.2....', 'text'),
 ('attributes.boardgameartist', 'text'),
 ('attributes.boardgamecategory', 'text'),
 ('attributes.boardgamecompilation', 'text'),
 ('attributes.boardgamedesigner', 'text'),
 ('attributes.boardgameexpansion', 'text'),
 ('attributes.boardgamefamily', 'text'),
 ('attributes.boardgameimplementation', 'text'),
 ('attributes.boardgameintegration', 'text'),
 ('attributes.boardgamemechanic', 'text'),
 ('attributes.boardgamepublisher', 'text'),
 ('row_names', 'text'),
 ('polls.language_dependence', 'text'),
 ('polls.suggested_numplayers.1', 'text'),
 ('polls.suggested_numplayers.10', 'text'),
 ('polls.suggested_numplayers.2', 'text'),
 ('polls.suggested_numplayers.3', 'text'),
 ('polls.suggested_numplayers.4', 'text'),
 ('polls.suggested_numplayers.5', 'text')]

In [14]:
conn.commit()

In [15]:
query = '''SELECT *
FROM "BoardGames"
LIMIT 5;'''

In [16]:
cur.execute(query)

In [17]:
first_five = cur.fetchmany(5)

In [18]:
first_five

[('1',
  '1',
  'boardgame',
  'Die Macher is a game about seven sequential political races in different regions of Germany. Players are in charge of national political parties, and must manage limited resources to help their party to victory. The winning party will have the most victory points after all the regional elections. There are four different ways of scoring victory points. First, each regional election can supply one to eighty victory points, depending on the size of the region and how well your party does in it. Second, if a party wins a regional election and has some media influence in the region, then the party will receive some media-control victory points. Third, each party has a national party membership which will grow as the game progresses and this will supply a fair number of victory points. Lastly, parties score some victory points if their party platform matches the national opinions at the end of the game.&#10;&#10;The 1986 edition featured 4 parties from the old West Germany and supported 3-4 players. The 1997 edition supports up to 5 players in the re-united Germany and updated several features of the rules as well.  The 2006 edition also supports up to 5 players and adds a shorter 5 round variant and additional rules updates by the original designer.&#10;&#10;Die Macher is #1 in the Valley Games Classic Line&#10;&#10;',
  '//cf.geekdo-images.com/images/pic159509.jpg',
  5,
  240,
  14,
  3,
  240,
  'Die Macher',
  240,
  '//cf.geekdo-images.com/images/pic159509_t.jpg',
  1986,
  'Marcus Gschwendtner',
  'Economic,Negotiation,Political',
  None,
  'Karl-Heinz Schmiel',
  None,
  'Country: Germany,Valley Games Classic Line',
  None,
  None,
  'Area Control / Area Influence,Auction/Bidding,Dice Rolling,Hand Management,Simultaneous Action Selection',
  'Hans im Gl√ºck Verlags-GmbH,Moskito Spiele,Valley Games, Inc.',
  6.0,
  7.66508,
  4.3477,
  7.29168,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  7.3957,
  85.0,
  None,
  None,
  None,
  None,
  0.0,
  1763.0,
  719.0,
  5251.0,
  1.59321,
  7.29168,
  147.0,
  170.0,
  4498.0,
  505.0,
  1654.0,
  'No',
  'NotRecommended',
  None,
  'NotRecommended',
  'NotRecommended',
  'Recommended',
  'Best',
  None,
  None,
  None,
  None,
  'NotRecommended',
  '14',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None),
 ('2',
  '2',
  'boardgame',
  "Dragonmaster is a trick-taking card game based on an older game called Coup d'etat. Each player is given a supply of plastic gems, which represent points. Each player will get to be the dealer for five different hands, with slightly different goals for each hand. After all cards have been dealt out, the dealer decides which hand best suits his or her current cards, and the other players are penalized points (in the form of crystals) for taking certain tricks or cards. For instance, if &quot;first&quot; or &quot;last&quot; is called, then a player is penalized for taking the first or last tricks. All players will get a chance to be dealer for five hands, but other players can steal this opportunity by taking all of the tricks during certain hands. At the end, the biggest pile of gems wins the game.&#10;&#10;Jewel contents:&#10;&#10;11 clear (3 extra)&#10;13 green (1 extra)&#10;22 red (2 extra)&#10;22 blue (2 extra)&#10;&#10;",
  '//cf.geekdo-images.com/images/pic184174.jpg',
  4,
  30,
  12,
  3,
  30,
  'Dragonmaster',
  30,
  '//cf.geekdo-images.com/images/pic184174_t.jpg',
  1981,
  'Bob Pepper',
  'Card Game,Fantasy',
  None,
  'G. W. "Jerry" D\'Arcey',
  None,
  'Animals: Dragons',
  "Indulgence,Coup d'etat",
  None,
  'Trick-taking',
  'E.S. Lowe,Milton Bradley',
  7.0,
  6.60815,
  1.9423,
  5.8715,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  5.91318,
  1066.0,
  None,
  None,
  None,
  None,
  0.0,
  273.0,
  52.0,
  1053.0,
  1.46282,
  5.8715,
  2541.0,
  73.0,
  478.0,
  67.0,
  161.0,
  'Some',
  'NotRecommended',
  None,
  'NotRecommended',
  'Recommended',
  'Best',
  None,
  None,
  None,
  None,
  None,
  'NotRecommended',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None),
 ('3',
  '3',
  'boardgame',
  'Part of the Knizia tile-laying trilogy, Samurai is set in medieval Japan. Players compete to gain the favor of three factions: samurai, peasants, and priests, which are represented by helmet, rice paddy, and Buddha tokens scattered about the board, which features the islands of Japan. The competition is waged through the use of hexagonal tiles, each of which help curry favor of one of the three factions &mdash; or all three at once! Players can make lightning-quick strikes with horseback ronin and ships or approach their conquests more methodically. As each token (helmets, rice paddies, and Buddhas) is surrounded, it is awarded to the player who has gained the most favor with the corresponding group.&#10;&#10;Gameplay continues until all the symbols of one type have been removed from the board or four tokens have been removed from play due to a tie for influence.&#10;&#10;At the end of the game, players compare captured symbols of each type, competing for majorities in each of the three types. Ties are not uncommon and are broken based on the number of other, &quot;non-majority&quot; symbols each player has collected.&#10;&#10;',
  '//cf.geekdo-images.com/images/pic3211873.jpg',
  4,
  60,
  10,
  2,
  30,
  'Samurai',
  60,
  '//cf.geekdo-images.com/images/pic3211873_t.jpg',
  1998,
  'Franz Vohwinkel',
  'Abstract Strategy,Medieval',
  None,
  'Reiner Knizia',
  None,
  'Asian Theme,Country: Japan,Knizia tile-laying trilogy,Samurai',
  None,
  None,
  'Area Control / Area Influence,Hand Management,Set Collection,Tile Placement',
  '999 Games,ABACUSSPIELE,Astrel Games,Ceilikan Jogos,Descartes Editeur,Edge Entertainment,Fantasy Flight Games,Galakta,Hans im Gl√ºck Verlags-GmbH,Hobby Japan,Lacerta,Lautapelit.fi,Rio Grande Games,Skandinavisk  Spil Kompagni,Wargames Club Publishing',
  6.0,
  7.44119,
  2.5085,
  7.28295,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  7.3061,
  112.0,
  None,
  None,
  None,
  None,
  0.0,
  3281.0,
  1355.0,
  11870.0,
  1.18531,
  7.28295,
  150.0,
  234.0,
  12019.0,
  707.0,
  2601.0,
  'No',
  'NotRecommended',
  None,
  'Recommended',
  'Best',
  'Recommended',
  None,
  None,
  None,
  None,
  None,
  'NotRecommended',
  '10',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None),
 ('4',
  '4',
  'boardgame',
  "When you see the triangular box and the luxurious, large blocks, you can tell this game was designed to be beautiful as well as functional.  The object of the game is to build pyramids out of the different colored blocks.  A pyramid scores more points when it's made from a few colors, but it's much harder to consistently outbid the other players for the necessary blocks.  The game is over when the Pharoah's Pyramid in the center is completed, which is built using all the blocks that the players don't use during the course of the game.&#10;&#10;Final round 1990 Hippodice Spieleautorenwettbewerb.&#10;&#10;",
  '//cf.geekdo-images.com/images/pic285299.jpg',
  4,
  60,
  12,
  2,
  60,
  'Tal der K√∂nige',
  60,
  '//cf.geekdo-images.com/images/pic285299_t.jpg',
  1992,
  None,
  'Ancient',
  None,
  'Christian Beierer',
  None,
  'Country: Egypt,Promotional Board Games',
  None,
  None,
  'Action Point Allowance System,Area Control / Area Influence,Auction/Bidding,Set Collection',
  'KOSMOS',
  5.0,
  6.60675,
  2.6667,
  5.76636,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  0.0,
  111.0,
  30.0,
  523.0,
  1.21028,
  5.76636,
  3191.0,
  29.0,
  314.0,
  61.0,
  112.0,
  'No',
  'NotRecommended',
  None,
  'Recommended',
  'Best',
  'Best',
  None,
  None,
  None,
  None,
  None,
  'NotRecommended',
  '14',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None),
 ('11',
  '11',
  'boardgame',
  "Bohnanza is the first in the Bohnanza family of games and has been published in several different editions.&#10;&#10;The cards are colorful depictions of beans in various descriptive poses, and the object is to make coins by planting fields (sets) of these beans and then harvesting them.  To help players match their cards up, the game features extensive trading and deal making.  One of the most unique features of the game is that you cannot rearrange your hand, as you need to play the cards in the order that you draw them.&#10;&#10;The original German edition supports 3-5 players.&#10;&#10;The English version from Rio Grande Games comes with the first edition of the first German expansion included in a slightly oversized box.  One difference in the contents, however, is that bean #22's Weinbrandbohne (Brandy Bean) was replaced by the Wachsbohne, or Wax Bean.  This edition includes rules for up to seven players, like the Erweiterungs-Set, but also adapts the two-player rules of Al Cabohne in order to allow two people to play Bohnanza.&#10;&#10;",
  '//cf.geekdo-images.com/images/pic69366.jpg',
  7,
  45,
  13,
  2,
  45,
  'Bohnanza',
  45,
  '//cf.geekdo-images.com/images/pic69366_t.jpg',
  1997,
  'Fr√©deric Bertrand,Marek Bl√°ha,Andrea Boekhoff,Klemens Franz,Oliver Freudenreich,Inge George,Guido Hoffmann,Alexander Jung,Harald Lieske,Atelier L√∂wentor,Doris Matth√§us,Bj√∂rn Pertoft,Uwe Rosenberg,Johann R√ºttinger,Barbara Stachuletz,Franz Vohwinkel,Markus Wagner',
  'Card Game,Farming,Negotiation',
  None,
  'Uwe Rosenberg',
  "Auf der schw√§b'schen Eisenbohn,Bohn Camillo,Bohnanza Erweiterungs-Set,Bohnanza Erweiterungs-Set (Revised Edition),Bohnanza: Amigo Bohnentaler,Bohnanza: Bean Market,Bohnanza: Bohnaparte & High Bohn,Bohnanza: Das Fanbuch,Bohnanza: Die Jokerbohnen,Bohnanza: Princes & Pirates,Bohnanza: Spiderbeans,Bohnaparte,Bohnedikt,Bohnedikt (2016 Edition),Bohnr√∂schen,Brettspiel Adventskalender 2015,Dschingis Bohn,Fasolki: Rozszerzenie,High Bohn,High Bohn Plus,High Bohn: Bohnenduell um 12 Uhr mittags,La Isla Bohnit√¢,Ladybohn,Mutabohn,Telebohn",
  'Bohnanza,Lookout Bean Games',
  'Bohn To Be Wild!,Bohnanza Fun & Easy,Bohnanza: 20 Jahre,My First Bohnanza,Sissi!: Die Bohnenkaiserin,Wendy Pferdebasar',
  None,
  'Hand Management,Set Collection,Trading',
  'AMIGO Spiel + Freizeit GmbH,999 Games,Brain Games,Copag - Cia. Paulista de Artes Gr√°ficas,Corfix,G3,Gigamic,Kaissa Chess & Games,Kikigagne?,Korea Boardgames co., Ltd.,Lautapelit.fi,Lifestyle Boardgames Ltd,Lookout Games,Mercurio,Midgaard Games,M√∂bius Games,Piatnik,Rio Grande Games,Stratelibri,Swan Panasia Co., Ltd.,Tempo Games',
  8.0,
  7.06751,
  1.6777,
  6.9828,
  None,
  None,
  None,
  None,
  None,
  None,
  6.98277,
  62.0,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  0.0,
  7030.0,
  2569.0,
  39474.0,
  1.27677,
  6.9828,
  336.0,
  730.0,
  28354.0,
  296.0,
  1782.0,
  'No',
  'NotRecommended',
  None,
  'NotRecommended',
  'Recommended',
  'Recommended',
  'Best',
  'Recommended',
  'Recommended',
  None,
  None,
  'NotRecommended',
  '8',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None)]

In [19]:
df5 = pd.DataFrame(first_five)

In [20]:
df5.head()

,0,1,2,3,4,5,6,7,8,9,...,71,72,73,74,75,76,77,78,79,80
0,1,1,boardgame,Die Macher is a game about seven sequential po...,//cf.geekdo-images.com/images/pic159509.jpg,5,240,14,3,240,...,None,None,None,None,None,None,None,None,None,None
1,2,2,boardgame,Dragonmaster is a trick-taking card game based...,//cf.geekdo-images.com/images/pic184174.jpg,4,30,12,3,30,...,None,None,None,None,None,None,None,None,None,None
2,3,3,boardgame,"Part of the Knizia tile-laying trilogy, Samura...",//cf.geekdo-images.com/images/pic3211873.jpg,4,60,10,2,30,...,None,None,None,None,None,None,None,None,None,None
3,4,4,boardgame,When you see the triangular box and the luxuri...,//cf.geekdo-images.com/images/pic285299.jpg,4,60,12,2,60,...,None,None,None,None,None,None,None,None,None,None
4,11,11,boardgame,Bohnanza is the first in the Bohnanza family o...,//cf.geekdo-images.com/images/pic69366.jpg,7,45,13,2,45,...,None,None,None,None,None,None,None,None,None,None

In [118]:
# column_names = [idx for idx, val in columns]
# column_names

In [119]:
# df5.columns = column_names

In [21]:
cur.execute('Select * FROM "BoardGames" LIMIT 0')

In [22]:
colnames = [desc[0] for desc in cur.description]

In [23]:
colnames

['row_names',
 'game.id',
 'game.type',
 'details.description',
 'details.image',
 'details.maxplayers',
 'details.maxplaytime',
 'details.minage',
 'details.minplayers',
 'details.minplaytime',
 'details.name',
 'details.playingtime',
 'details.thumbnail',
 'details.yearpublished',
 'attributes.boardgameartist',
 'attributes.boardgamecategory',
 'attributes.boardgamecompilation',
 'attributes.boardgamedesigner',
 'attributes.boardgameexpansion',
 'attributes.boardgamefamily',
 'attributes.boardgameimplementation',
 'attributes.boardgameintegration',
 'attributes.boardgamemechanic',
 'attributes.boardgamepublisher',
 'attributes.total',
 'stats.average',
 'stats.averageweight',
 'stats.bayesaverage',
 'stats.family.abstracts.bayesaverage',
 'stats.family.abstracts.pos',
 'stats.family.cgs.bayesaverage',
 'stats.family.cgs.pos',
 'stats.family.childrensgames.bayesaverage',
 'stats.family.childrensgames.pos',
 'stats.family.familygames.bayesaverage',
 'stats.family.familygames.pos',
 'stats.family.partygames.bayesaverage',
 'stats.family.partygames.pos',
 'stats.family.strategygames.bayesaverage',
 'stats.family.strategygames.pos',
 'stats.family.thematic.bayesaverage',
 'stats.family.thematic.pos',
 'stats.family.wargames.bayesaverage',
 'stats.family.wargames.pos',
 'stats.median',
 'stats.numcomments',
 'stats.numweights',
 'stats.owned',
 'stats.stddev',
 'stats.subtype.boardgame.bayesaverage',
 'stats.subtype.boardgame.pos',
 'stats.trading',
 'stats.usersrated',
 'stats.wanting',
 'stats.wishing',
 'polls.language_dependence',
 'polls.suggested_numplayers.1',
 'polls.suggested_numplayers.10',
 'polls.suggested_numplayers.2',
 'polls.suggested_numplayers.3',
 'polls.suggested_numplayers.4',
 'polls.suggested_numplayers.5',
 'polls.suggested_numplayers.6',
 'polls.suggested_numplayers.7',
 'polls.suggested_numplayers.8',
 'polls.suggested_numplayers.9',
 'polls.suggested_numplayers.Over',
 'polls.suggested_playerage',
 'attributes.t.links.concat.2....',
 'stats.family.amiga.bayesaverage',
 'stats.family.amiga.pos',
 'stats.family.arcade.bayesaverage',
 'stats.family.arcade.pos',
 'stats.family.atarist.bayesaverage',
 'stats.family.atarist.pos',
 'stats.family.commodore64.bayesaverage',
 'stats.family.commodore64.pos',
 'stats.subtype.rpgitem.bayesaverage',
 'stats.subtype.rpgitem.pos',
 'stats.subtype.videogame.bayesaverage',
 'stats.subtype.videogame.pos']

In [28]:
df5.columns = colnames

In [33]:
pd.set_option('max_colwidth', 100)
df5

  row_names game.id  game.type                                                                                  details.description                                 details.image  details.maxplayers  details.maxplaytime  details.minage  details.minplayers  details.minplaytime  ... stats.family.arcade.bayesaverage  stats.family.arcade.pos stats.family.atarist.bayesaverage  stats.family.atarist.pos stats.family.commodore64.bayesaverage stats.family.commodore64.pos stats.subtype.rpgitem.bayesaverage stats.subtype.rpgitem.pos stats.subtype.videogame.bayesaverage stats.subtype.videogame.pos
0         1       1  boardgame  Die Macher is a game about seven sequential political races in different regions of Germany. Pla...   //cf.geekdo-images.com/images/pic159509.jpg                   5                  240              14                   3                  240  ...                             None                     None                              None                      None                                  None                         None                               None                      None                                 None                        None
1         2       2  boardgame  Dragonmaster is a trick-taking card game based on an older game called Coup d'etat. Each player ...   //cf.geekdo-images.com/images/pic184174.jpg                   4                   30              12                   3                   30  ...                             None                     None                              None                      None                                  None                         None                               None                      None                                 None                        None
2         3       3  boardgame  Part of the Knizia tile-laying trilogy, Samurai is set in medieval Japan. Players compete to gai...  //cf.geekdo-images.com/images/pic3211873.jpg                   4                   60              10                   2                   30  ...                             None                     None                              None                      None                                  None                         None                               None                      None                                 None                        None
3         4       4  boardgame  When you see the triangular box and the luxurious, large blocks, you can tell this game was desi...   //cf.geekdo-images.com/images/pic285299.jpg                   4                   60              12                   2                   60  ...                             None                     None                              None                      None                                  None                         None                               None                      None                                 None                        None
4        11      11  boardgame  Bohnanza is the first in the Bohnanza family of games and has been published in several differen...    //cf.geekdo-images.com/images/pic69366.jpg                   7                   45              13                   2                   45  ...                             None                     None                              None                      None                                  None                         None                               None                      None                                 None                        None

[5 rows x 81 columns]

In [34]:
df5.shape

(5, 81)

In [18]:
conn.commit()

In [4]:
import pandas as pd

In [12]:
df = pd.read_csv('data/dailygas.csv')
df.head()

         Date  Price
0  1997-01-07   3.82
1  1997-01-08   3.80
2  1997-01-09   3.61
3  1997-01-10   3.92
4  1997-01-13   4.00

In [13]:
df.tail()

            Date  Price
5948  2020-08-26   2.52
5949  2020-08-27   2.52
5950  2020-08-28   2.46
5951  2020-08-31   2.30
5952  2020-09-01   2.22

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5953 entries, 0 to 5952
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    5953 non-null   object
 1   Price   5952 non-null   float64
dtypes: float64(1), object(1)
memory usage: 93.1+ KB

In [17]:
ufodf = pd.read_csv('data/ufoscrubbed.csv')
ufodf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80332 entries, 0 to 80331
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   datetime              80332 non-null  object
 1   city                  80332 non-null  object
 2   state                 74535 non-null  object
 3   country               70662 non-null  object
 4   shape                 78400 non-null  object
 5   duration (seconds)    80332 non-null  object
 6   duration (hours/min)  80332 non-null  object
 7   comments              80317 non-null  object
 8   date posted           80332 non-null  object
 9   latitude              80332 non-null  object
 10  longitude             80332 non-null  float64
dtypes: float64(1), object(10)
memory usage: 6.7+ MB

/home/zy/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (5,9) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [18]:
ufodf.head()

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.941111
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.581082
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.916667
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.803611

In [19]:
ufodf.columns

Index(['datetime', 'city', 'state', 'country', 'shape', 'duration (seconds)',
       'duration (hours/min)', 'comments', 'date posted', 'latitude',
       'longitude '],
      dtype='object')

In [20]:
earthquake_df = pd.read_csv('data/earthquakes.csv')
earthquake_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23412 entries, 0 to 23411
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        23412 non-null  object
 1   Time                        23412 non-null  object
 2   Latitude                    23412 non-null  float64
 3   Longitude                   23412 non-null  float64
 4   Type                        23412 non-null  object
 5   Depth                       23412 non-null  float64
 6   Depth Error                 4461 non-null   float64
 7   Depth Seismic Stations      7097 non-null   float64
 8   Magnitude                   23412 non-null  float64
 9   Magnitude Type              23409 non-null  object
 10  Magnitude Error             327 non-null    float64
 11  Magnitude Seismic Stations  2564 non-null   float64
 12  Azimuthal Gap               7299 non-null   float64
 13  Horizontal Distance         1604 non-null   float64
 14  Horizontal Error            1156 non-null   float64
 15  Root Mean Square            17352 non-null  float64
 16  ID                          23412 non-null  object
 17  Source                      23412 non-null  object
 18  Location Source             23412 non-null  object
 19  Magnitude Source            23412 non-null  object
 20  Status                      23412 non-null  object
dtypes: float64(12), object(9)
memory usage: 3.8+ MB

In [21]:
earthquake_df.head()

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,1/2/1965,13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,1/4/1965,11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,1/5/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,1/8/1965,18:49:43,-59.076,-23.557,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,1/9/1965,13:32:50,11.938,126.427,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic

In [22]:
earthquake_df.columns

Index(['Date', 'Time', 'Latitude', 'Longitude', 'Type', 'Depth', 'Depth Error',
       'Depth Seismic Stations', 'Magnitude', 'Magnitude Type',
       'Magnitude Error', 'Magnitude Seismic Stations', 'Azimuthal Gap',
       'Horizontal Distance', 'Horizontal Error', 'Root Mean Square', 'ID',
       'Source', 'Location Source', 'Magnitude Source', 'Status'],
      dtype='object')

In [23]:
dataAnalyst_df = pd.read_csv('data/DataAnalyst.csv')
dataAnalyst_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2253 entries, 0 to 2252
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         2253 non-null   int64
 1   Job Title          2253 non-null   object
 2   Salary Estimate    2253 non-null   object
 3   Job Description    2253 non-null   object
 4   Rating             2253 non-null   float64
 5   Company Name       2252 non-null   object
 6   Location           2253 non-null   object
 7   Headquarters       2253 non-null   object
 8   Size               2253 non-null   object
 9   Founded            2253 non-null   int64
 10  Type of ownership  2253 non-null   object
 11  Industry           2253 non-null   object
 12  Sector             2253 non-null   object
 13  Revenue            2253 non-null   object
 14  Competitors        2253 non-null   object
 15  Easy Apply         2253 non-null   object
dtypes: float64(1), int64(2), object(13)
memory usage: 281.8+ KB

In [24]:
dataAnalyst_df.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
0,0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True
1,1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1
2,2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We‚Äôre looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1
3,3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1
4,4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True

In [25]:
import dataframe_image as dfi

In [26]:
dfi.export(dataAnalyst_df, 'df_styled.png', max_rows=5)

OSError: Chrome executable not able to be found on your machine